name: Lighthouse CI

on:
  deployment_status:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Audit Preview URL with Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
            ${{ github.event.deployment_status.target_url }}/dashboard
            ${{ github.event.deployment_status.target_url }}/profile
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: ./.lighthouserc.json
